// AUTOGENERATED by make_unicode_tables.awk from the output of
// go/src/pkg/unicode/maketables.go.  Yes it's awful, but frankly
// it's quicker than porting 1300 more lines of Go.

package re2s

object UnicodeTables {
  final val CATEGORIES: Map[String, Array[Array[Int]]] = ???
  final val FOLD_CATEGORIES: Map[String, Array[Array[Int]]] = ???  
  final val SCRIPTS: Map[String, Array[Array[Int]]] = ???
  final val FOLD_SCRIPT: Map[String, Array[Array[Int]]] = ???
  final val CASE_ORBIT: Array[Array[Int]] = ???
  final val CASE_RANGES: Array[Array[Int]] = ???
  final val L: Array[Array[Int]] = ???
  final val Lower: Array[Array[Int]] = ???
  final val M: Array[Array[Int]] = ???
  final val N: Array[Array[Int]] = ???
  final val P: Array[Array[Int]] = ???
  final val S: Array[Array[Int]] = ???
  final val Title: Array[Array[Int]] = ???
  final val Upper: Array[Array[Int]] = ???
  final val UpperCase  = 0
  final val LowerCase  = 1
}

